### ISSUE TITLE
[Feature Request] Support for remote-related extensions to VSCode

### ISSUE THREAD

**Issue by yaegassy** [artakase/vscode-yamafiler#1]
Thank you so much for creating such a wonderful extension.

Can you support remote-related extensions to VSCode?

- [Remote - SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh)
- [Dev Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers)
- [WSL](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl)

**Comment by yaegassy** [comment]
I have checked that the `yamafiler.useRecommendedKeybindings` setting does not seem to be respected for remote-extension related cases.

I was able to confirm that it works to some extent by explicitly adding the following settings to the VSCode `keybindings.json`.

- <https://github.com/artakase/vscode-yamafiler/blob/880f40a405ac3eb0395d916bb4af8b145db21c5a/package.json#L162-L324>

Also, Unfortunately, the `yamafiler.delete` command for the delete function does not work correctly in remote extension environments. There may be other functions that do not work as well. :(

The following are the environments I tested the feature in:

- Mac (Remote - SSH)
- Windows (WSL)

**Comment by artakase** [comment]
Thank you for your report. I would like to support remote extensions.

Please apply this workaround to `keybindings.json`:
```json 
{
    "key": "d",
    "command": "yamafiler.delete",
    "args": {
        "useTrash": false
    },
    "when": "resourceScheme == yamafiler && editorTextFocus"
},

```

**Comment by yaegassy** [comment]
Hi, Thank you for checking the issue.

I have added the `args` setting for the `yamafiler.delete` command in the `keybindings.json` file and confirmed that it works correctly.
